import os
import argparse
import pandas as pd
import matplotlib.pyplot as plt

def plot_csv_losses(csv_path, save_path="loss_curve.png"):
    """
    Reads the progress.csv file generated by Stable Baselines 3 logger
    and plots the policy gradient loss and value loss curves.
    """
    print(f"Looking for training logs in: {csv_path}")
    
    if not os.path.exists(csv_path):
        print(f"\n[ERROR] The file '{csv_path}' does not exist.")
        print("This file is needed to plot the loss curve.")
        print("\nStable Baselines 3 doesn't save loss curves automatically unless explicitly configured.")
        print("I have updated your 'train_ppo.py' script so that the next time you train,")
        print("it will automatically generate this 'progress.csv' file without needing TensorBoard.")
        print("\nPlease run training again for a few episodes/timesteps to generate the loss data:")
        print("    python train_ppo.py")
        return

    print("Loading data...")
    df = pd.read_csv(csv_path)

    # Clean up column names (SB3 sometimes has trailing/leading spaces)
    df.columns = df.columns.str.strip()

    # The typical keys SB3 logs
    loss_keys = [
        'train/loss', 
        'train/policy_gradient_loss', 
        'train/value_loss'
    ]
    
    # Check which loss metrics were actually logged
    found_keys = [k for k in loss_keys if k in df.columns and df[k].notna().any()]
    
    if not found_keys:
        print(f"\n[ERROR] Could not find any valid loss columns in {csv_path}.")
        print(f"Available columns: {list(df.columns)}")
        return

    # Use time/total_timesteps for x-axis if available, otherwise just use rows (updates)
    if 'time/total_timesteps' in df.columns:
        x_axis = df['time/total_timesteps']
        x_label = 'Total Timesteps'
    elif 'time/episodes' in df.columns:
        x_axis = df['time/episodes']
        x_label = 'Episodes'
    else:
        x_axis = range(len(df))
        x_label = 'Training Updates'

    plt.figure(figsize=(10, 6))
    
    for key in found_keys:
        # Drop NaNs just for this specific curve to avoid breaks in the plot line
        valid_data = df[[x_axis.name if isinstance(x_axis, pd.Series) else None, key]].dropna()
        
        if not valid_data.empty:
            plt.plot(valid_data.iloc[:, 0] if isinstance(x_axis, pd.Series) else range(len(valid_data)), 
                     valid_data[key], label=key.split('/')[-1])
        
    plt.title('PPO Training Loss Curve')
    plt.xlabel(x_label)
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    
    plt.savefig(save_path)
    print(f"\n-> Loss curve plotted successfully and saved to {save_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Plot Loss Curve from SB3 progress.csv")
    parser.add_argument("--csv-path", type=str, default="runs/ppo/progress.csv", help="Path to the progress.csv log file")
    parser.add_argument("--save-path", type=str, default="loss_curve.png", help="Where to save the plot")
    
    args = parser.parse_args()
    
    plot_csv_losses(args.csv_path, args.save_path)
